# Generated by Django 5.1.2 on 2024-10-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='language_level',
            field=models.IntegerField(default=1),
        ),
    ]
