# Generated by Django 5.1.2 on 2024-10-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_age_user_current_level_user_energy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.CreateModel(
            name='KazakhTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('language_level', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kazakh_tests', to='api.userprofile')),
            ],
        ),
    ]
